application: numeric-incline-526
version: 1
runtime: python27
instance_class: F4
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/portal/img/favicon.ico
  upload: static/portal/img/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png

- url: /static
  static_dir: static
  application_readable: true
  secure: always

- url: /.*
  script: main.application
  secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: 'deploy.settings'
  DATABASE_NAME: 'deploy'
  CACHE_PREFIX: 'prod-'
  HTTPS: 'on'

libraries:
- name: MySQLdb
  version: latest
- name: ssl
  version: latest

automatic_scaling:
  max_pending_latency: 30ms
