application: numeric-incline-526
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: integrate

handlers:
- url: /favicon\.ico
  static_files: static/portal/img/favicon.ico
  upload: static/portal/img/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static
  application_readable: true
  secure: always

- url: /.*
  script: main.application
  secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: 'deploy.settings'
  DATABASE_NAME: 'codeforlife_integrate'
  CACHE_PREFIX: 'integrate-'

libraries:
- name: MySQLdb
  version: latest
- name: PIL
  version: latest
