application: decent-digit-629
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: dev

handlers:
- url: /favicon\.ico
  static_files: static/portal/img/favicon.ico
  upload: static/portal/img/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png

- url: /apple-touch-icon-76x76\.png
  static_files: static/apple-touch-icon-76x76.png
  upload: static/apple-touch-icon-76x76\.png

- url: /apple-touch-icon-120x120\.png
  static_files: static/apple-touch-icon-120x120.png
  upload: static/apple-touch-icon-120x120\.png

- url: /apple-touch-icon-152x152\.png
  static_files: static/apple-touch-icon-152x152.png
  upload: static/apple-touch-icon-152x152\.png

- url: /apple-touch-icon-180x180\.png
  static_files: static/apple-touch-icon-180x180.png
  upload: static/apple-touch-icon-180x180\.png

- url: /static
  static_dir: static
  application_readable: true
  secure: always

- url: /_ah/stats.*
  script: google.appengine.ext.appstats.ui.app
  secure: always

- url: /.*
  script: main.application
  secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: 'deploy.settings'
  DATABASE_NAME: 'cfl_dev'
  CACHE_PREFIX: 'dev-'

libraries:
- name: MySQLdb
  version: latest
- name: PIL
  version: latest

builtins:
- appstats: on

skip_files:
- ^(.*/)?.*\.scss$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^lib\/.*info$
- ^lib\/PIL
